export const TASK_TYPE = {
    UNBLOCK_NODE: 'UNBLOCK_NODE',
    ACTIVATE_NODE: 'ACTIVATE_NODE',
    CREATE_EDGE: 'CREATE_EDGE',
    ASSIGN_FACTORY_NODE: 'ASSIGN_FACTORY_NODE',
    SHIP_CREATED: 'SHIP_CREATED',
}